//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_9D_MVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public string existencia { get; set; }
        public int precio { get; set; }
        public int id { get; set; }
    }
}
